services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: pantrytrack
      POSTGRES_PASSWORD: pantrytrack
      POSTGRES_DB: pantrytrack
    ports:
      - "5432:5432"
    volumes:
      - pantrytrack-postgres:/var/lib/postgresql/data

volumes:
  pantrytrack-postgres:
